spring:
  application:
    name: netbanking-service
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 2224
  
  error:
    whitelabel:
      enabled: false